### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RodneyOnyi**
I found this.props  and extraProps wasn't working. I think this is shorter and fits better into an existing dialog design.

### CODE REVIEW

**Comment by mmazzarolo** [comment]
I think you edited the wrong example, the one that used `state` was the fist one . 
Let me know if I'm missing something... thanks!

**Comment by RodneyOnyi** [comment]
I tried the given example but it wasn't responsive hence the edit I was suggesting.

**Comment by mmazzarolo** [comment]
That's because it's not a full example, it's only focused to show how the Dialog accepts React-Native-Modal props 👍 (in that case you need to pass them from the outstide)

**Comment by RodneyOnyi** [comment]
Thanks for the clarification.

**Pull request closed without merging**
