### PR TITLE
add additional styling to Dialog.Container

### PR DESCRIPTION
**Pull request by intergalactic-overlords**
Hi, I would like to have more possibilities for styling Dialog.Container. In this pull request, I have added the following extra properties to Dialog.Container:
* contentStyle
* headerStyle
* footerStyle
* buttonSeparatorStyle

These styles allow the user to add extra styling or override existing styling. I does not automatically completely replace the original styling.

Personally I will use this to adjust the width of the dialog on IOS and make the header more narrow on both IOS and Android. 

But since I thought this is something somebody else might want, here's a pull request ;-)

### CODE REVIEW

**Comment by mmazzarolo** [comment]
Hey! Thank you for submitting this PR!

> Personally I will use this to adjust the width of the dialog on IOS and make the header more narrow on both IOS and Android.

Would these changes make the dialog UI looks more "native"? 
Because if it is the case we might even implement your changes directly in the package (since the aim of `react-native-dialog` is to match the native UI as much as possible)!

**Comment by intergalactic-overlords** [comment]
Hi there :-)
It won't exactly make it more "native". As you probably know, the native dialog (especially on IOS) is very rigid. When you want to do something special (in native), you need to roll your own.

The nice thing about react-native-dialog off course is, that you can choose your own content and that you're not restricted to only text. I also wanted a bit more flexibility in styling.

What this pull-request does, is give developers a lot more customisation possibilities, especially towards styling. It makes it possible to adjust the layout of the dialog to different types of contents and/or to different types of designs.

In my specific case, the content I need to show is quite wide and the dialog width on IOS is fixed on 270px. I wanted to make it wider, similar to the android dialog. Also the IOS header is too tall and I wanted to make it narrower (because the designer said so :-p).

**Comment by mmazzarolo** [comment]
Gotcha, thank you @intergalactic-overlords :) Merged!

**Comment by mmazzarolo** [comment]
Landed in [v5.5.0](https://github.com/mmazzarolo/react-native-dialog/releases/tag/v5.5.0)

**Pull request merged**
